/** Declaration file generated by dts-gen */

export const headless: boolean

export const mode: string

export const themes: {}

export function addSequencer(a: any, b: any): void

export function black(a: string): string

export function blue(a: string): string

export function bold(a: string): string

export function cyan(a: string): string

export function gray(a: string): string

export function green(a: string): string

export function grey(a: string): string

export function install(): string

export function inverse(a: string): string

export function italic(a: string): string

export function magenta(a: string): string

export function rainbow(a: string): string

export function red(a: string): string

export function setTheme(a: string): string

export function strikethrough(a: string): string

export function strip(a: string): string

export function stripColors(a: string): string

export function underline(a: string): string

export function uninstall(): string

export function white(a: string): string

export function yellow(a: string): string

export function zebra(a: string): string

export namespace addSequencer {
  const prototype: {}
}

export namespace black {
  const prototype: {}
}

export namespace blue {
  const prototype: {}
}

export namespace bold {
  const prototype: {}
}

export namespace cyan {
  const prototype: {}
}

export namespace gray {
  const prototype: {}
}

export namespace green {
  const prototype: {}
}

export namespace grey {
  const prototype: {}
}

export namespace install {
  const prototype: {}
}

export namespace inverse {
  const prototype: {}
}

export namespace italic {
  const prototype: {}
}

export namespace magenta {
  const prototype: {}
}

export namespace rainbow {
  const prototype: {}
}

export namespace red {
  const prototype: {}
}

export namespace setTheme {
  const prototype: {}
}

export namespace strikethrough {
  const prototype: {}
}

export namespace strip {
  const prototype: {}
}

export namespace stripColors {
  const prototype: {}
}

export namespace underline {
  const prototype: {}
}

export namespace uninstall {
  const prototype: {}
}

export namespace white {
  const prototype: {}
}

export namespace yellow {
  const prototype: {}
}

export namespace zebra {
  const prototype: {}
}
